### ISSUE TITLE
Reconcile - component k8s service type can't be overridden in the env specific config file.

### ISSUE THREAD

**Issue by marcinc** [appvia/kev#288] opened 2020-10-02 15:13 UTC
It looks like it's impossible to override the K8s service type for compose services auto-inferred as LoadBalancer.

To replicate get an example compose service spec, e.g.:

```yaml
version: '3'
services:
  mongo:
    image: mongo:3.2
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017

volumes:
  mongo-data:
```  

then override k8s service type in env specific override, e.g.:

```yaml
version: "3"
services:
  mongo:
    labels:
      kev.service.type: clusterip
```

Reconciler will persist the `kev.service.type` label, however its value will revert to that originally inferred from the source compose i.e. LoadBalancer.

**Comment by ezodude** [comment] 2020-10-12 13:27
As discussed before, this is by design since we view the `kev.service.type` as specialised configuration better handled internally by `Kev`.

**I propose re-working this as a new feature rather than a bug.**

Here's a proposal that can allow more informed developers to force an override,
- Introduce a new `reconcile-exclude` param in `kev.yaml`.
- `reconcile-exclude`, enables a developer to exclude specific service labels from reconciliation - as they know best.
- For now, it will only affect `kev.service.type` (its the only label that is affected by the base changes).
- If the service is removed, reconciliation will also remove the `reconcile-exclude.<service>` from `kev.yaml`.

Here's a draft of how this would look:
```yaml
compose:
  - docker-compose.yaml
environments:
  dev:
    source: docker-compose.kev.dev.yaml
    reconcile-exclude:
      db:
      - "kev.service.type"
  staging:
    source: docker-compose.kev.staging.yaml
```

**Comment by marcinc** [comment] 2020-10-12 15:16
If this is not surfaced to the end user (i.e. transparent) then we could go with the above. kev.service.type is a key element that user should be able to override. And this will be potentially true for other things. 
I wasn't aware of such behaviour in the reconciler so assumed it was a bug, because it doesn't meet the functional requirements.

**Comment by ezodude** [comment] 2020-10-12 15:39
@marcinc Making this work as reported is simple, we just stop reconciling upstream updates to the K8s service type.

The reason it works as it is now, is that developers configure the service type implicitly. They simply change the `ports` config and we infer what that means.

IMO, I would personally like `kev` to take care of this for me. And then, allow power to users to wield their will per environment. 

(happy to discuss some more)

**Comment by marcinc** [comment] 2020-10-12 16:36
But that precisely the point. Kev takes care of it at the moment so in most cases it should work, however, if for whatever reason you don't like that choice or have a particular use case you should be able to override it and have that choice persisted. Detail of what's stored in kev.yaml isn't end user's concern so am OK with the approach above.

**Comment by ezodude** [comment] 2020-10-13 08:23
I think we need 5 - 10 min brainstorm to think / work this through - including how it works internally.

**Comment by marcinc** [comment] 2020-10-13 10:19
How about we initially derive service type from the compose project (as we do currently) and make it visible in the env overrides, so that it's obvious to the user as to what to change? 

Any consecutive changes to the source Compose could potentially result in different derived service type, which is fine - just this time the information will be immediately visible to the user as service type config parameter will be included in the reduced list. 

Also, when service type change has been noticed it'd be good to communicate that to the user with notable changes section or something to highlight it better...

**Comment by marcinc** [comment] 2020-10-13 12:59
OK, so I’d approach that in the following way:

1. Init -> service type discovered and added to environment configs
2. Reconcile -> derives service types (as it does currently),
    1. if derived type is the same as what’s in the environment:
        1. Nothing do to here - no need to communicate anything to the user! 
    2. If derived type is different than current environment override value
        1. Notify the difference to the user e.g. “- App component X appears to require LoadBalancer but it’ll use ClusterIP service as defined in dev environment config!”

This way, we basically say that first time we always derive the service type, and notify the user about the discrepancies in the configuration if they diverge over time.

**Comment by ezodude** [comment] 2020-10-14 09:57
Addressed by https://github.com/appvia/kev/issues/299

**Closed** 2020-10-14 09:56 UTC
Labels: bug
